name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger from GitHub Actions page

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: jithubaiju55 # Replace with your GitHub username
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push the Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate Snake Animation"
          git push
